# This is a basic workflow that is manually triggered

name: Sync Stroyblok when main updated

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  syncContent:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: NPM - Clear cache
        shell: pwsh
        run: |
          npm cache clean --force
          npm install
          npm install storyblok -g
          storyblok pull-components --space 23811
          storyblok sync --type folders,components,stories --source 238118 --target 240970
